Follow akashic-engine@3.0.0-beta.35
akashic-games/game-driver pull request #44
Opened 2020-10-23 03:56 UTC by yu-ogi

## このPullRequestが解決する内容
akashic-games/akashic-engine#254 に追従します。

2020-10-23 04:57 UTC, xnv requested changes

2020-10-23 04:57 UTC, xnv commented on src/EventBuffer.ts
> +				this._unfilteredEvents.push(pev);
local event を 積まれる可能性もあるので `EventBuffer.isEventLocal()` で判別して `_unfilteredLocalEvents` に振り分けたいです。

2020-10-23 04:57 UTC, xnv commented on src/EventBuffer.ts
> +			processNext: (pev: pl.Event): void => {
すいません akashic-engine 側で見落としたんですが、これ複数渡せるようにしませんか。

というのも、現実的には「フィルタが配列で受け取ったイベント列を頭から順に処理していき、途中で抜ける必要が発生した時、 "残りを全部" 次のフレームに持ち越す」というユースケースが大半ではないかと思うからです。配列で受け取り配列で返すイベントフィルタとの対称性を考えても、ここは配列で取れる方がストレートに思えます。

「ピンポイントでイベント一つ先送りして、その後に続くイベントは処理する」ということも、まあないとは言い切れませんが、受信した順序を無視することになるので割とトリッキーに思えます。

2020-10-23 04:57 UTC, xnv commented on src/EventBuffer.ts
> +				this._unfilteredEvents.push(pev);
これこうして改めて見ると「単に push() してる」のは一見危うい処理 (下手なタイミングで呼ばれたらイベントの順序が狂うように見える) ですね……。次の前提があるので問題ないはずですが、この辺の事情をコメントに残しておきたいです。

- この関数は `processEvents()` が呼び出すイベントフィルタから同期的にしか呼び出されない。(呼び出されてはならない)
-  `processEvents()` は `_unfilteredEvents` などを空にして、同期的にイベントフィルタを呼ぶ
- 従ってこの関数が呼ばれる時、 `_unfilteredEvents` などに後続の (次フレーム以降に処理される) イベントが積まれている可能性はない
- よって単純に push() しても、後続のイベントとの順序が崩れる可能性はない

Akashic Engine 側の `processNext()` のコメントにも「イベントフィルタの中から同期的にのみ呼び出すことができる」旨書いておいた方がいいかもですね。(現実的にこの制約に反する使い方はまずしないと思いますが)

2020-10-23 05:58 UTC, yu-ogi commented on src/EventBuffer.ts
> +			processNext: (pev: pl.Event): void => {
最初は複数渡せるようなインタフェース定義を検討していたのですが、実装してみると単一で渡せた方が利用側にとって都合が良さそうと判断して今の形にしました。

理由は以下になります。
* イベントフィルタの実装は `pevs` を `for` でループさせるのが大半であり、for の中で `pevs.slice()` 等を呼び出して `break` するよりも、`for` の内部で処理している単数のイベントを都度 push する方が (個人的には) わかりやすい
* `JoinEvent` のようにシーンに依存しないイベントも存在するので、そのようなイベントを (あえて) 遅延させたくない場合は「JoinEvent の前後で pevs を分割して slice する」というような複雑なロジックが必要となる

> イベントフィルタとの対称性を考えても、ここは配列で取れる方がストレートに思えます。

これは確かにそうですね。
とはいえイベントフィルタと processNext() では扱うイベントの対象が異なる (前者はゲーム全体に対する1フレームのイベント群・後者はイベントそのもの) と考えることもできそうで、個人的にはそこまで違和感はありませんでした。

2020-10-23 06:28 UTC, yu-ogi commented on src/EventBuffer.ts
> +				this._unfilteredEvents.push(pev);
なるほど、ありがとうございます。
こちら修正しました。 13bb7d4

2020-10-23 06:29 UTC, yu-ogi commented on src/EventBuffer.ts
> +				this._unfilteredEvents.push(pev);
なるほど、おっしゃるとおりですね。
こちらコメント追加しました。 80d27e3

2020-10-23 07:07 UTC, ShinobuTakahashi approved these changes

2020-10-26 05:14 UTC, xnv commented on src/EventBuffer.ts
> +			processNext: (pev: pl.Event): void => {
うーん。なるほど。私はフィルタの引数の `pevs` を `shift()` しながらループするつもりで考えていたんですが、単純に `for` で回す方が無駄はないですね。そうすると、 `processNext()` する時に `slice()` が必要にはなってしまう。

> for の中で pevs.slice() 等を呼び出して break するよりも、for の内部で処理している単数のイベントを都度 push する方が (個人的には) わかりやすい

なので大筋いいようなきがしていますが、一応。ここは引っかかっています。つまりこうするのが良いということでしょうか。

```javascript
function filter(pevs, filterController) {
  let needsInterrupt = false;

  for (let i = 0; i < pevs.length; ++i) {
    const pev = pevs[i];
    if (needsInterrupt) {
      filterController.processNext(pev);
      continue;
    }
    switch (pev ...) {
       // 元々のイベントフィルタの処理
       case ...:
          if (...) {  // 抜けるべきとなったらフラグを立てる
            needsInterrupt = true;
          }
    }
  }
}
```

`needsInterrupt` のフラグが関数内でどう変更されるのか完全に把握しないと動作が追えなくなっていて、これはさすがにわかりやすさの話をするなら下の方がよいのでは。

```javascript
function filter(pevs, filterController) {
  for (let i = 0; i < pevs.length; ++i) {
    const pev = pevs[i];
    switch (pev ...) {
       // 元々のイベントフィルタの処理
       case ...:
          if (...) {  // 抜けるべきとなったら全部次に回して抜ける
            pevs.slice(i + 1).map(pev => filterController.processNext(pev));
            retrun ...;
          }
    }
  }
}
```

まあここで slice() するか for 回すかはコンテンツ作者に委ねればいいので、結論として単数系にするのは了解です。

2020-10-26 05:19 UTC, xnv approved these changes

2020-10-26 22:58 UTC, merged